### ISSUE TITLE
consolidate application.conf and load it from $MEGAM_HOME

### ISSUE THREAD

**Issue by thomasalrin** [megamsys/megam_gateway#217]

**Comment by thomasalrin** [comment]
UI take application-production.conf, and binary takes application.conf.
If we don't need these two, please remove anyone, and let's keep one conf.

**Comment by indykish** [comment]
lets load it from /var/lib/megam ($MEGAM_HOME)

**Comment by indykish** [comment]
@thomasalrin  read the pull request, we have one file called `/var/lib/megam/megamgateway/gateway.conf` where `/var/lib/megam` is `MEGAM_HOME`
