### ISSUE TITLE
megam_gateway doesn't get MEGAM_HOME env variable 

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/megam_gateway#242]

**Comment by vijaykanthm28** [comment]
but the gateway runs when we place marketplaces.yaml at /usr/share/megam/megamgateway/bin/

**Comment by rajthilakmca** [comment]
set gateway.conf to MEGAM_HOME/megamgateway/ location

**Comment by thomasalrin** [comment]
Print MEGAM_HOME in log, so that we can debug easily.
Temporary fix as @indykish said, Load MEGAM_HOME from gateway.conf

**Comment by indykish** [comment]
Cool, as the last resort we have the option of loading it from `gateway.conf` file with the following setting.

```
megam.marketplaces = ${?MEGAM_HOME}/megamgateway/marketplaces.yaml
```

`upstart` to have.

```
-Dconfig.file=/var/lib/megam/megamgateway/gateway.conf

```

**Comment by indykish** [comment]
@megamsys/megam-dev  There is a fix. Needs verification.

**Comment by indykish** [comment]
The fix works.
