### ISSUE TITLE
billedhistories, sensors, balances table structure is differ from cqlsh table to vertice.cql file, so i can drop the table in cqlsh and create table manually from vertice.cql structure.

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/megam_gateway#378]
UPDATE vertice.billedhistories SET currency_type = ?, id = ?, billing_amount = ? WHERE bill_type = ? AND created_at = ? AND account_id = ? AND assembly_id = ? [  0.1 VM 05 Jul 16 09:51 UTC  ASM7166146125846809972]
time="2016-07-05T09:51:31Z" level=debug msg="PRIMARY KEY part id found in SET part" 
time="2016-07-05T09:51:31Z" level=warning msg="Failed to process watch event: PRIMARY KEY part id found in SET part"

**Comment by indykish** [comment]
@rajesh-rajagopal  Rajesh, you need to `vertice.cql` first. Then you need to run `upgrade-1.5.cql` ? Did your run that way ?

**Comment by indykish** [comment]
@rajesh-rajagopal  Got it after our discussion, make that change in `upgrade-1.5.cql`
