### ISSUE TITLE
set ssl in cassandra, it require ssl flag for login

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/megam_gateway#413]
setting ssl in cqlsh using username and password in need ssl flag for login

eg:  cqlsh --ssl -u vertice -p vertice 
it successfully works. 

In gateway conf we send the username and password only, but it need ssl flag for login. adding ssl flag to solve this issue.

**Comment by indykish** [comment]
@rajesh-rajagopal  Good job in tightening security fixes for prod deployment.

Seems like `ssl` will be an overkill now for 1.5. We'll go with `userid` and `pw` only.

This is already built in to the gwy code. 

```

  Cluster.builder()
      .addContactPoints(hosts)
      .withCredentials(MConfig.scylla_username, MConfig.scylla_password)
      .build()

```

In 2.0 we are already `rusty` :)

Lets publish your cassandra work in our new `devcenter` in `netlify` next week.

**Comment by indykish** [comment]
@rajesh-rajagopal  

As this done, please document, and push an article  on `ssl cassandra` 

### 1. github.com/megamsys/devcenter.megam.io

### 2. update docs.megam.io with the manual steps needed as we have included userid/password.

When done, please review it with @ranjithamca

**Comment by rajesh-rajagopal** [comment]
ok sir.. 
I will create an article for setting **ssl for cassandra.**
and update the steps for setup userid/password in cassandra - docs.megam.io

**Comment by ranjithamca** [comment]
#413 issue closed
