### ISSUE TITLE
Applications needs the port to run 

### ISSUE THREAD

**Issue by vinomca-megam** [megamsys/megam_gateway#435]
Update the port for the application in marketplace item

**Custom App**
nodejs port : 9001
java: 8080
php : /current 
pythons: (need  the port)
rails:(need the port)
play: 9000

**Oneclick App**
hadoop 
spark 
sparknotebook
zarafa 
owncloud
rabbitMQ
riak

**Comment by ranjithamca** [comment]
python:80
zarafa: /webaccess
spark: 9004
hadoop: 50070
spark-notebook: 9000
rabbitMq: 15672
riak : 8098
c/c++,redis,postgresql: There is no http port.

**Comment by indykish** [comment]
Lets add in the next release.

### envs:

Please add `http_suffix_url:`  needed only for `zarafa` and `php`

@ranjithamca
