### ISSUE TITLE
Records not updated in billingtranscation table

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/megam_gateway#437]
i got  response from whmcs page into gateway, but this record is not " updated in billingtransactions table". and set "Approved = true" in "accounts" table

Oct 19 18:37:20 megamswasa verticegateway[49305]: [debug] application - ====> 192.168.0.118:9000/v2/billingtransactions/content
Oct 19 18:37:20 megamswasa verticegateway[49305]: [debug] application - HEAD: ArrayBuffer((Host,192.168.0.118:9000), (Accept,application/json), (Content-Type,application/json), (Accept-Encoding,gzip), (User-Agent,megam-api/v2), (X-Megam-DATE,2016-10-19 18:37), (X-Megam-HMAC,rrrajthilak@gmail.com:7c5917671214152a829913c2b45d939aeab39b0940c8bb3cec33fdbcea4d8172), (X-Megam-ORG,ORG7995500728416993473), (Content-Length,130))
Oct 19 18:37:20 megamswasa verticegateway[49305]: [debug] application - BODY: {"gateway":"offlinecc","amountin":"11.47","amountout":0,"fees":"0.00","tranid":"","trandate":"19\/10\/2016","currency_type":"USD"}
Oct 19 18:37:20 megamswasa verticegateway[49305]: [debug] application - MEMCACHE:            -->[getAs ?1]
Oct 19 18:37:20 megamswasa verticegateway[49305]: [debug] application - Master key id ->     -->[1]
Oct 19 18:37:20 megamswasa verticegateway[49305]: [debug] application - MEMCACHE:            -->[getAs ?rrrajthilak@gmail.com]
Oct 19 18:37:20 megamswasa verticegateway[49305]: [debug] application - LIV                  -->[rrrajthilak@gmail.com]
Oct 19 18:37:20 megamswasa verticegateway[49305]: [debug] application - GOOF                 -->[email/api-key  ✘]

**Comment by rajesh-rajagopal** [comment]
Fix to need :- update the trigger response details in **billingtransactions** table and **approved=true** in **account** table

**Comment by indykish** [comment]
@rajesh-rajagopal  Great job man.  @rajthilakmca  Good that you helped nail the culprit :)
