### ISSUE TITLE
Delete - Stop/Start is not working for container

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/megam_gateway#505]
There is a common queue in NSQ for container.
But stop/start request are listening a separate queue in NSQ. 
So its not work.

![image](https://cloud.githubusercontent.com/assets/18652643/22141421/0672cba4-df18-11e6-8e1d-14a8d6ab6cfe.png)

![image](https://cloud.githubusercontent.com/assets/18652643/22141436/1381c336-df18-11e6-91bb-c2b92c537ac7.png)

**Comment by indykish** [comment]
This is fixed, https://github.com/megamsys/vertice/pull/381

**Comment by indykish** [comment]
and other nilavu fixes.
