### ISSUE TITLE
external_objects table to store and sync contents of external systems to Vertice

### ISSUE THREAD

**Issue by rathishvbr** [megamsys/megam_gateway#534]
The problem arises where we need a manifestation of 3rd party systems into us.

For instance 
`machine is => assembly`, in the same way a 
`quota is => order in the billing system WHMCS`.

The API will support 

1. external_objects/:id will return 

```json
{id: "EXT0001",
  object_id" "123456",
 account_id: "test@email.com", 
 inputs: [{ key: "quota_id" , value: "QUO000001"}]
}
```

2. external_objects/content will post data when it receives

```json
{object_id" "123456",
  inputs: [{ key: "quota_id" , value: "QUO000001"}]
}
```

**Comment by rathishvbr** [comment]
{:id, :object_id, :account_id, :inputs{:k,:v}}

**Comment by indykish** [comment]
#530
