### ISSUE TITLE
Data model changes in rawimages table 

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/megam_gateway#572]
'{"source":"images","url":"http://archive.ubuntu.com/ubuntu/dists/xenial/main/installer-amd64/current/images/netboot/mini.iso","properties":[]}'

need without enclosing of single quote with repos field in rawimages table 

{"source":"images","url":"http://archive.ubuntu.com/ubuntu/dists/xenial/main/installer-amd64/current/images/netboot/mini.iso","properties":[]}

**Comment by indykish** [comment]
Like `components.repos`
