### ISSUE TITLE
Use onboard nsq events message with encrypted password

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/megam_gateway#606]
when user onboard 
gateway trigger message to nsq events queue 
with base64 encrypted password on inputs field {"id":"","accounts_id":"ACT5563357690126932758","type":"user","action":"4","inputs":[{"key":"email","value":"mvijaykanth@megam.io"},{"key":"nilavu_password","value":"MUef3rtymKu="}]}

**Comment by indykish** [comment]
key will be `password_hash` which is base64 strict encoded.

**Comment by indykish** [comment]
@vijaykanthm28  Please test it out.
