### ISSUE TITLE
Need route for getting single backup by using  admin email id and admin api key

### ISSUE THREAD

**Issue by suganyakaliyamoorthy** [megamsys/megam_gateway#612]

**Comment by indykish** [comment]
@vijaykanthm28 @rathishvbr   I need to design doc. Hence returning it.

@vijaykanthm28  @rajthilakmca  @vinomca-megam @suganyakaliyamoorthy  @rathishvbr  I am tired to write APIs, since the full fledged functions in 1.5.2 have not proceed to closure.
