### ISSUE TITLE
Need two additional field  (label, privileges)

### ISSUE THREAD

**Issue by suganyakaliyamoorthy** [megamsys/megam_gateway#613]
Label need as array type because label  going to hold list of user.
privileges need as string type because privilege going to hold  mode of backup privileges(private or public)

**Comment by indykish** [comment]
@vijaykanthm28 @rathishvbr   I need to design doc. Don't have clue why this is needed. Hence returning it.

@vijaykanthm28  @rajthilakmca  @vinomca-megam @suganyakaliyamoorthy  @rathishvbr  I am tired to writing APIs, since the full fledged functions in 1.5.2 have not proceeded to closure.
